# Generated by Django 2.1.4 on 2019-04-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sec', models.CharField(blank=True, max_length=1, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('district', models.CharField(blank=True, max_length=30, null=True)),
                ('village', models.CharField(blank=True, max_length=30, null=True)),
                ('glocation', models.CharField(blank=True, max_length=100, null=True)),
                ('profilelink1', models.CharField(blank=True, max_length=100, null=True)),
                ('profiilelink2', models.CharField(blank=True, max_length=100, null=True)),
                ('landref', models.CharField(blank=True, max_length=100, null=True)),
                ('markref', models.CharField(blank=True, max_length=30, null=True)),
                ('farmerid', models.CharField(blank=True, max_length=30, null=True)),
                ('lastmodified', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'farmer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=10)),
                ('lastlogin', models.DateField(blank=True, null=True)),
                ('idattr1', models.CharField(blank=True, db_column='idAttr1', max_length=10, null=True)),
                ('idattr2', models.CharField(blank=True, db_column='idAttr2', max_length=10, null=True)),
                ('idattr3', models.CharField(blank=True, db_column='idAttr3', max_length=10, null=True)),
                ('uid', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'identity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Landinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmerid', models.CharField(blank=True, max_length=30, null=True)),
                ('soiltype', models.CharField(blank=True, max_length=20, null=True)),
                ('watersource', models.CharField(blank=True, max_length=20, null=True)),
                ('landsize', models.FloatField(blank=True, null=True)),
                ('sizetype', models.CharField(blank=True, max_length=10, null=True)),
                ('cattletype', models.CharField(blank=True, max_length=10, null=True)),
                ('cattlenumber', models.IntegerField(blank=True, null=True)),
                ('cattlebreed', models.CharField(blank=True, max_length=20, null=True)),
                ('corpinfo1', models.CharField(blank=True, max_length=50, null=True)),
                ('cropinfo2', models.CharField(blank=True, max_length=50, null=True)),
                ('cropinfo3', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'landinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Markinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmerid', models.CharField(blank=True, max_length=30, null=True)),
                ('year', models.DateField(blank=True, null=True)),
                ('profit', models.FloatField(blank=True, null=True)),
                ('trend', models.IntegerField(blank=True, null=True)),
                ('market', models.CharField(blank=True, max_length=30, null=True)),
                ('minfo1', models.CharField(blank=True, max_length=30, null=True)),
                ('minfo3', models.CharField(blank=True, max_length=30, null=True)),
                ('minfo2', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'markinfo',
                'managed': False,
            },
        ),
    ]
